name: upgrader
description: Flutter package for prompting users to upgrade when there is a newer version of the app in the store.
version: 7.1.0
homepage: https://github.com/larryaasen/upgrader

environment:
  sdk: '>=2.17.0 <4.0.0'
  # flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # From fluttercommunity.dev: Get current device information from within the Flutter application.
  device_info_plus: ^11.1.1

  # Pure Dart library for HTML5 parsing
  html: ^0.15.5

  # From Dart Team: A composable, Future-based library for making HTTP requests.
  http: ^1.2.2

  # From dart.dev: Platform independent access to information about the current operating system.
  os_detect: ^2.0.2

  # From Flutter Community: Provides an API for querying information about an application package.
  package_info_plus: ^8.1.1

  # From Flutter Team: Wraps NSUserDefaults (on iOS) and SharedPreferences (on Android).
  shared_preferences: ^2.3.3

  # From Flutter Team: A Flutter plugin for launching a URL in the mobile platform.
  url_launcher: ^6.3.1

  # A dart library for comparing and incrementing version numbers with Semantic Versioning.
  version: ^3.0.2

  # A dart library for parsing, traversing, querying, transforming and building XML documents.
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # From Dart Team: Mock library for Dart inspired by Mockito.
  mockito: ^5.4.4
  flutter_lints: ^5.0.0

# flutter:
